### ISSUE TITLE
Gaussian in 6-slam funWithParameters.py 358-361

### ISSUE THREAD

**Issue by WolsYang** [jeremy-shannon/udacity-AI-for-robotics#2]
Hi, Jeremy
I have some questions at 358-361.

I think in here is doing a gaussian right?

`359 sqrt(2.0 * pi * (self.measurement_noise ** 2))`

but in gaussian I think it should be 

`sqrt(2.0 * pi ) * self.measurement_noise` 

Why in this case I should put sigma in sqrt() ? 

I can't understand:(

**Comment by jeremy-shannon** [comment]
Sorry @WolsYang, I have no idea. You'll have to ask Udacity about that.
